stages:
  - build
  - release

variables:
  BINARY_NAME: "beszel-agent_windows_amd64.exe"
  UPSTREAM_REPO_URL: "https://github.com/henrygd/beszel.git"
  LHM_REPO_URL: "https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.git"
  GITLAB_DOMAIN: "https://gitlab.prplanit.com"
  OUTPUT_DIR: "beszel-agent_windows_amd64-$CI_COMMIT_TAG"
  ZIP_NAME: "$OUTPUT_DIR.zip"

build-release:
  before_script: |
    echo "---------------------------------------------------------------------------"
    echo "AntParade GitOps 🐜 - Preparing $CI_JOB_IMAGE image for build..."
    echo "---------------------------------------------------------------------------"
    echo "Installing dependencies... (git, zip, wget, curl, libicu)"
    apt-get update && apt-get install -y git zip wget curl libicu67
    
    # Install .NET 8 SDK (which can build .NET Framework 4.8)
    wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    chmod +x dotnet-install.sh
    bash ./dotnet-install.sh --channel 8.0 --install-dir /usr/share/dotnet
    ln -s /usr/share/dotnet/dotnet /usr/local/bin/dotnet
    export PATH="/usr/share/dotnet:$PATH"
    
    # Verify installations
    dotnet --version
    go version
  environment: production
  image: golang:1.24.5-bullseye
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script: |
    echo "---------------------------------------------------------------------------"
    echo "AntParade GitOps 🐜 - Building $OUTPUT_DIR with LibreHardwareMonitor..."
    echo "---------------------------------------------------------------------------"
    
    # Clone Beszel first (we don't need to build LibreHardwareMonitor separately!)
    echo "Cloning the $CI_COMMIT_TAG branch of $UPSTREAM_REPO_URL..."
    git clone --depth 1 --branch $CI_COMMIT_TAG $UPSTREAM_REPO_URL
    cd beszel/beszel
    
    echo "Preparing Go dependencies..."
    go mod tidy
    
    # Build the LibreHardwareMonitor wrapper as per official docs
    echo "Building LibreHardwareMonitor .NET wrapper (required for Windows builds)..."
    dotnet build -c Release ./internal/agent/lhm/beszel_lhm.csproj
    
    # Verify the LHM build created the expected files
    echo "=== Checking LibreHardwareMonitor build output ==="
    find ./internal/agent/lhm -name "*.dll" | head -10
    find ./internal/agent/lhm -type d -name "net48" -exec echo "Found net48: {}" \; -exec ls -la {} \;
    
    # Build Beszel agent
    cd cmd/agent
    echo "Building $BINARY_NAME from the source for $OUTPUT_DIR..."
    echo "Building with LibreHardwareMonitor support..."
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-w -s" -o $BINARY_NAME

    echo "Packaging release into $ZIP_NAME..."
    mkdir -p "$CI_PROJECT_DIR/$OUTPUT_DIR"
    mv $BINARY_NAME "$CI_PROJECT_DIR/$OUTPUT_DIR/"
    cd "$CI_PROJECT_DIR"
    zip -r "$ZIP_NAME" "$OUTPUT_DIR"

    echo "$ZIP_NAME has been packaged, here are its details:"
    ls -lh "$ZIP_NAME"
    
    echo "AntParade GitOps 🐜 - build-release job complete."

  artifacts:
    paths:
      - "$ZIP_NAME"
    expire_in: 1 week

create-release:
  before_script:  |
    echo "---------------------------------------------------------------------------"
    echo "AntParade GitOps 🐜 - Preparing $CI_JOB_IMAGE image for release upload tasks"
    echo "---------------------------------------------------------------------------"
    echo "Installing dependencies... (bash curl jq)"
    apk add --no-cache bash curl jq                                                       >/dev/null
  dependencies:
    - build-release
  stage: release
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG
  script: |
    echo "---------------------------------------------------------------------------"
    echo "AntParade GitOps 🐜 - Begin tasks for upload of $BINARY_NAME $CI_COMMIT_TAG"
    echo "---------------------------------------------------------------------------"
    echo "Creating release $CI_COMMIT_TAG..."
    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --request POST \
      --form "name=Release $CI_COMMIT_TAG" \
      --form "tag_name=$CI_COMMIT_TAG" \
      --form "description=AntParade GitOps 🐜 packaged $CI_COMMIT_TAG release of $CI_PROJECT_NAME." \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases" || echo "Release might already exist"                                     >/dev/null

    echo "Uploading $ZIP_NAME to the $CI_PROJECT_NAME gitlab package registry..."
    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --upload-file "$ZIP_NAME" \
        "$GITLAB_DOMAIN/api/v4/projects/$CI_PROJECT_ID/packages/generic/beszel-agent/$CI_COMMIT_TAG/$ZIP_NAME"                    >/dev/null

    echo "Need to determine the uploaded package's URL..."
    echo "Getting packages for project..."
    PACKAGE_JSON=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages")

    PACKAGE_ID=$(echo "$PACKAGE_JSON" | jq -r '.[] | select(.name=="beszel-agent" and .version=="'"$CI_COMMIT_TAG"'") | .id')

    if [ -z "$PACKAGE_ID" ]; then
      echo "❌ No matching package found for version $CI_COMMIT_TAG"
      exit 1
    fi

    echo "Found Package ID: $PACKAGE_ID"

    echo "Fetching package files..."
    PACKAGE_FILE_JSON=$(curl --silent --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/$PACKAGE_ID/package_files")

    PACKAGE_FILE_ID=$(echo "$PACKAGE_FILE_JSON" | jq '.[0].id')

    if [ -z "$PACKAGE_FILE_ID" ] || [ "$PACKAGE_FILE_ID" = "null" ]; then
      echo "❌ No package files found"
      exit 1
    fi

    PACKAGE_LINK="${GITLAB_DOMAIN}/${CI_PROJECT_PATH}/-/package_files/${PACKAGE_FILE_ID}/download"
    echo "✅ The uploaded package's URL is $PACKAGE_LINK."

    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
      --request POST \
      --header "Content-Type: application/json" \
      --data "{\"name\":\"$ZIP_NAME\",\"url\":\"$PACKAGE_LINK\",\"link_type\":\"package\"}" \
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
    
    echo "AntParade GitOps 🐜 - create-release job complete."
