stages:
  - build
  - release

variables:
  BINARY_NAME: "beszel-agent_windows_amd64.exe"
  GITLAB_DOMAIN: "https://gitlab.prplanit.com"
  OUTPUT_DIR: "agent_windows_amd64-$CI_COMMIT_TAG"
  ZIP_NAME: "$OUTPUT_DIR.zip"

build-release:
  artifacts:
    paths:
      - "$ZIP_NAME"
  before_script:  |
    echo "Setting up Go build environment..."
    echo "Installing dependencies... (git)"
    apk add --no-cache git zip
  environment: production
  image: golang:1.24.5-alpine3.22
  rules:
    - if: $CI_COMMIT_TAG
  stage: build
  script: |
    echo "Cloning tagged release- $CI_COMMIT_TAG"
    git clone --depth 1 --branch $CI_COMMIT_TAG https://github.com/henrygd/beszel.git
    cd beszel/beszel/cmd/agent

    echo "Building binary..."
    GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-w -s" -o $BINARY_NAME

    echo "Packaging release..."
    mkdir -p "$CI_PROJECT_DIR/$OUTPUT_DIR"
    mv $BINARY_NAME "$CI_PROJECT_DIR/$OUTPUT_DIR/"
    cd "$CI_PROJECT_DIR"
    zip -r "$ZIP_NAME" "$OUTPUT_DIR"

    echo "Copying zip to project directory for release upload"
    mv "$ZIP_NAME" "$CI_PROJECT_DIR/"

create-release:
  artifacts:
    paths:
      - "$ZIP_NAME"
  stage: release
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script: |
    echo "Creating release $CI_COMMIT_TAG"
    curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --request POST \
      --form "name=Release $CI_COMMIT_TAG" \
      --form "tag_name=$CI_COMMIT_TAG" \
      --form "description=Automated release for $CI_COMMIT_TAG" \
      "https://$GITLAB_DOMAIN/api/v4/projects/$CI_PROJECT_ID/releases"
    echo "Uploading asset..."
    curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --upload-file "$ZIP_NAME" \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/uploads" > upload_response.json
    UPLOAD_URL=$(jq -r '.url' upload_response.json)
    echo "Adding asset link to release- $UPLOAD_URL"
    curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --request POST \
      --header "Content-Type: application/json" \
      --data "{\"name\":\"$ZIP_NAME\",\"url\":\"https://$GITLAB_DOMAIN/$CI_PROJECT_PATH$UPLOAD_URL\"}" \
      "https://$GITLAB_DOMAIN/api/v4/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"